security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        authenticated_user_provider:
            id: Todo\Infrastructure\Security\AuthenticatedUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - Todo\Infrastructure\Security\TodoAuthenticator
            logout:
                path: logout

    access_control:
         - { path: ^/login, , role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: ROLE_USER }

